import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SessionWrapper from "components/SessionWrapper";
import TanstackProvider from "components/TanstackProvider";
import { Toaster } from 'react-hot-toast';
import AuthNavbar from "components/AuthNavbar";
import { auth } from "../auth";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session=await auth();
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-black`}>
      <SessionWrapper>
        <TanstackProvider>
        <Toaster 
        position="bottom-right"
        toastOptions={{
          duration:2000,
          style: {
            background: '#111',
            color: '#fff',
             border: '1px solid #2a2a2a',
             borderRadius: '10px',
          },
        }}
      />
      <div className="flex flex-col min-h-screen">
        <div className="sticky top-0 z-50 bg-black/60 backdrop-blur-md">
          <AuthNavbar session={session}/>
        </div>

        <main className="flex-1">
          {children}
        </main>
      </div>
      </TanstackProvider>
      </SessionWrapper>
    </body>

    </html>
  );
}
